[executable]
    type=FILE_EXE

[directory]
    type=DIR

[device]
    type=DEVICE

[special]
    type=SPECIAL

[stalelink]
    type=STALE_LINK

[symlink]
    type=SYMLINK

[core]
    regexp=^core\\.*\\d*$
    extensions_case=true

[temp]
    extensions=bak;cache;log;old;orig;tmp

[archive]
    extensions=7z;ace;alz;apk;arc;arj;bz;bz2;cab;cpio;crate;deb;gz;jar;lha;lrz;lz;lz4;lzma;lzo;rar;rpm;tar;tbz;tbz2;tgz;tlz;txz;xz;zip;zst

[doc]
    extensions=djvu;doc;docx;epub;md;odf;odt;pdf;rtf;tex;txt

[source]
    extensions=c;cc;clj;cpp;cs;css;go;h;hpp;html;java;js;jsx;lua;nix;php;py;rb;rs;scss;sh;toml;ts;tsx;vim;zig

[media]
    extensions=aac;flac;m4a;mid;midi;mp3;ogg;opus;wav

[graph]
    extensions=avif;bmp;gif;jpeg;jpg;jxl;mkv;mov;mp4;mpeg;mpg;png;svg;svgz;tif;tiff;webm;webp

[database]
    extensions=dat;db;dbf;mdb;pgsql;sql;sqlite;sqlite3

# Hardlinks have lowest precedence to make them colored by file type or extension
[hardlink]
    type=HARDLINK
