use crate::file_kinds::{
    file_extension_groups, push_file_kind_source, resolve_file_kind_color, FileKind,
};
use crate::report::{dropped_items, role_source, ExportReport, PreservedItem};
use palette16::{color, Base16Palette};
use semantic_roles::{role_color, Role, SemanticRoles};
use theme_ir::{parse_rgb, ResolvedTheme, Warning};

pub fn export_mc_skin(
    theme: &ResolvedTheme,
    roles: &SemanticRoles,
    palette: &Base16Palette,
    warnings: Vec<Warning>,
) -> (String, ExportReport) {
    let export = export_mc(theme, roles, palette, warnings);
    (export.skin_ini, export.report)
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct McExport {
    pub skin_ini: String,
    pub filehighlight_ini: String,
    pub colortable_env: String,
    pub report: ExportReport,
}

pub fn export_mc(
    theme: &ResolvedTheme,
    roles: &SemanticRoles,
    palette: &Base16Palette,
    warnings: Vec<Warning>,
) -> McExport {
    let mut output = String::new();
    output.push_str("[skin]\n");
    output.push_str(&format!(
        "    description = {} - generated by Helix Theme Transformer\n",
        theme.name
    ));
    output.push_str("    truecolors = true\n");
    output.push('\n');
    output.push_str("[Lines]\n");
    for (key, value) in mc_lines() {
        output.push_str(&format!("    {key} = {value}\n"));
    }

    for section in mc_sections() {
        output.push('\n');
        output.push_str(&format!("[{}]\n", section.name));
        for entry in section.entries {
            output.push_str(&format!(
                "    {} = {}\n",
                entry.key,
                render_entry(&entry, roles, palette)
            ));
        }
    }

    let report = ExportReport {
        exporter: "mc".to_owned(),
        source: theme.source_path.to_string(),
        preserved: mc_preserved_items(roles),
        dropped: mc_dropped_items(theme),
        warnings,
    };
    McExport {
        skin_ini: output,
        filehighlight_ini: export_mc_filehighlight(),
        colortable_env: export_mc_colortable(roles, palette),
        report,
    }
}

pub fn export_mc_filehighlight() -> String {
    let mut output = String::new();
    output.push_str("[executable]\n    type=FILE_EXE\n\n");
    output.push_str("[directory]\n    type=DIR\n\n");
    output.push_str("[device]\n    type=DEVICE\n\n");
    output.push_str("[special]\n    type=SPECIAL\n\n");
    output.push_str("[stalelink]\n    type=STALE_LINK\n\n");
    output.push_str("[symlink]\n    type=SYMLINK\n\n");
    output.push_str("[core]\n    regexp=^core\\\\.*\\\\d*$\n    extensions_case=true\n\n");

    for group in mc_filehighlight_groups() {
        output.push_str(&format!("[{}]\n", group.section));
        output.push_str(&format!(
            "    extensions={}\n\n",
            group.extensions.join(";")
        ));
    }

    output.push_str(
        "# Hardlinks have lowest precedence to make them colored by file type or extension\n",
    );
    output.push_str("[hardlink]\n    type=HARDLINK\n");
    output
}

pub fn export_mc_colortable(roles: &SemanticRoles, palette: &Base16Palette) -> String {
    let mut output = String::new();
    output.push_str("# Generated by Helix Theme Transformer\n");
    output.push_str("export MC_COLOR_TABLE='");

    for (index, entry) in mc_colortable_entries().iter().enumerate() {
        if index > 0 {
            output.push(':');
        }
        output.push_str(entry.key);
        output.push('=');
        output.push_str(&resolve_colortable_color(entry.fg, roles, palette));
        output.push(',');
        output.push_str(&resolve_colortable_color(entry.bg, roles, palette));
        if !entry.attrs.is_empty() {
            output.push(',');
            output.push_str(&entry.attrs.join("+"));
        }
    }

    output.push_str("'\n");
    output
}

#[derive(Debug, Clone)]
struct McSection {
    name: &'static str,
    entries: Vec<McEntry>,
}

#[derive(Debug, Clone, Copy)]
struct McEntry {
    key: &'static str,
    fg: McColor,
    bg: McColor,
    attrs: &'static [&'static str],
}

#[derive(Debug, Clone, Copy)]
struct McColorTableEntry {
    key: &'static str,
    fg: McColor,
    bg: McColor,
    attrs: &'static [&'static str],
}

#[derive(Debug, Clone, Copy)]
enum McColor {
    Role {
        roles: &'static [Role],
        fallback_base: &'static str,
    },
    FileKind(FileKind),
}

impl McColor {
    const fn new(roles: &'static [Role], fallback_base: &'static str) -> Self {
        Self::Role {
            roles,
            fallback_base,
        }
    }

    const fn file_kind(kind: FileKind) -> Self {
        Self::FileKind(kind)
    }
}

const BACKGROUND: McColor = McColor::new(&[Role::Background], "base00");
const SURFACE: McColor = McColor::new(&[Role::Surface], "base01");
const SELECTION: McColor = McColor::new(&[Role::Selection], "base02");
const FOREGROUND: McColor = McColor::new(&[Role::Foreground], "base05");
const MUTED_FOREGROUND: McColor = McColor::new(&[Role::MutedForeground], "base03");
const BRIGHT_FOREGROUND: McColor = McColor::new(&[Role::BrightForeground], "base07");
const TYPE: McColor = McColor::new(&[Role::Type], "base0A");
const SPECIAL: McColor = McColor::new(&[Role::Special], "base0C");
const ERROR: McColor = McColor::new(&[Role::Error], "base08");
const WARNING: McColor = McColor::new(&[Role::Warning, Role::Type], "base0A");
const GIT_ADDED: McColor = McColor::new(&[Role::GitAdded], "base0B");
const FILE_DIRECTORY: McColor = McColor::file_kind(FileKind::Directory);
const FILE_SYMLINK: McColor = McColor::file_kind(FileKind::Symlink);
const FILE_EXECUTABLE: McColor = McColor::file_kind(FileKind::Executable);
const FILE_DEVICE: McColor = McColor::file_kind(FileKind::Device);
const FILE_BROKEN_LINK: McColor = McColor::file_kind(FileKind::BrokenLink);
const FILE_ARCHIVE: McColor = McColor::file_kind(FileKind::Archive);
const FILE_DOCUMENT: McColor = McColor::file_kind(FileKind::Document);
const FILE_SOURCE: McColor = McColor::file_kind(FileKind::Source);
const FILE_IMAGE_VIDEO: McColor = McColor::file_kind(FileKind::ImageVideo);
const FILE_DATABASE: McColor = McColor::file_kind(FileKind::Database);
const FILE_TEMPORARY: McColor = McColor::file_kind(FileKind::Temporary);
const FILE_GIT_ADDED: McColor = McColor::file_kind(FileKind::GitAdded);
const FILE_GIT_MODIFIED: McColor = McColor::file_kind(FileKind::GitModified);
const FILE_GIT_REMOVED: McColor = McColor::file_kind(FileKind::GitRemoved);

const BOLD: &[&str] = &["bold"];
const ITALIC: &[&str] = &["italic"];
const UNDERLINE: &[&str] = &["underline"];

fn mc_lines() -> &'static [(&'static str, &'static str)] {
    &[
        ("horiz", "─"),
        ("vert", "│"),
        ("lefttop", "┌"),
        ("righttop", "┐"),
        ("leftbottom", "└"),
        ("rightbottom", "┘"),
        ("topmiddle", "┬"),
        ("bottommiddle", "┴"),
        ("leftmiddle", "├"),
        ("rightmiddle", "┤"),
        ("cross", "┼"),
        ("dhoriz", "═"),
        ("dvert", "║"),
        ("dlefttop", "╔"),
        ("drighttop", "╗"),
        ("dleftbottom", "╚"),
        ("drightbottom", "╝"),
        ("dtopmiddle", "╤"),
        ("dbottommiddle", "╧"),
        ("dleftmiddle", "╟"),
        ("drightmiddle", "╢"),
    ]
}

const fn entry(key: &'static str, fg: McColor, bg: McColor, attrs: &'static [&str]) -> McEntry {
    McEntry { key, fg, bg, attrs }
}

const fn color_table_entry(
    key: &'static str,
    fg: McColor,
    bg: McColor,
    attrs: &'static [&str],
) -> McColorTableEntry {
    McColorTableEntry { key, fg, bg, attrs }
}

fn mc_sections() -> Vec<McSection> {
    vec![
        McSection {
            name: "core",
            entries: vec![
                entry("_default_", FOREGROUND, BACKGROUND, &[]),
                entry("selected", FOREGROUND, SELECTION, &[]),
                entry("marked", WARNING, BACKGROUND, BOLD),
                entry("markselect", WARNING, SELECTION, BOLD),
                entry("gauge", FOREGROUND, SURFACE, &[]),
                entry("input", FOREGROUND, SURFACE, &[]),
                entry("inputmark", FOREGROUND, SELECTION, &[]),
                entry("inputunchanged", MUTED_FOREGROUND, SURFACE, &[]),
                entry("disabled", MUTED_FOREGROUND, SURFACE, &[]),
                entry("reverse", BACKGROUND, FOREGROUND, &[]),
                entry("commandlinemark", FOREGROUND, SELECTION, &[]),
                entry("header", TYPE, BACKGROUND, BOLD),
                entry("shadow", MUTED_FOREGROUND, BACKGROUND, &[]),
            ],
        },
        McSection {
            name: "dialog",
            entries: vec![
                entry("_default_", FOREGROUND, SURFACE, &[]),
                entry("dfocus", BACKGROUND, SELECTION, BOLD),
                entry("dhotnormal", WARNING, SURFACE, &[]),
                entry("dhotfocus", WARNING, SELECTION, BOLD),
                entry("dtitle", TYPE, SURFACE, BOLD),
            ],
        },
        McSection {
            name: "error",
            entries: vec![
                entry("_default_", FOREGROUND, ERROR, &[]),
                entry("errdfocus", BACKGROUND, WARNING, BOLD),
                entry("errdhotnormal", WARNING, ERROR, &[]),
                entry("errdhotfocus", WARNING, SELECTION, BOLD),
                entry("errdtitle", WARNING, ERROR, BOLD),
            ],
        },
        McSection {
            name: "filehighlight",
            entries: vec![
                entry("directory", FILE_DIRECTORY, BACKGROUND, BOLD),
                entry("executable", FILE_EXECUTABLE, BACKGROUND, BOLD),
                entry("symlink", FILE_SYMLINK, BACKGROUND, &[]),
                entry("hardlink", FILE_SYMLINK, BACKGROUND, &[]),
                entry("stalelink", FILE_BROKEN_LINK, BACKGROUND, &[]),
                entry("device", FILE_DEVICE, BACKGROUND, &[]),
                entry("special", FILE_SYMLINK, BACKGROUND, &[]),
                entry("core", FILE_BROKEN_LINK, BACKGROUND, &[]),
                entry("temp", FILE_TEMPORARY, BACKGROUND, &[]),
                entry("archive", FILE_ARCHIVE, BACKGROUND, &[]),
                entry("doc", FILE_DOCUMENT, BACKGROUND, &[]),
                entry("source", FILE_SOURCE, BACKGROUND, &[]),
                entry("media", FILE_IMAGE_VIDEO, BACKGROUND, &[]),
                entry("graph", FILE_IMAGE_VIDEO, BACKGROUND, &[]),
                entry("database", FILE_DATABASE, BACKGROUND, &[]),
            ],
        },
        McSection {
            name: "menu",
            entries: vec![
                entry("_default_", FOREGROUND, SURFACE, &[]),
                entry("menusel", FOREGROUND, SELECTION, &[]),
                entry("menuhot", WARNING, SURFACE, &[]),
                entry("menuhotsel", WARNING, SELECTION, &[]),
                entry("menuinactive", MUTED_FOREGROUND, SURFACE, &[]),
            ],
        },
        McSection {
            name: "popupmenu",
            entries: vec![
                entry("_default_", FOREGROUND, SURFACE, &[]),
                entry("menusel", FOREGROUND, SELECTION, &[]),
                entry("menutitle", TYPE, SURFACE, BOLD),
            ],
        },
        McSection {
            name: "buttonbar",
            entries: vec![
                entry("hotkey", WARNING, SURFACE, BOLD),
                entry("button", FOREGROUND, SURFACE, &[]),
            ],
        },
        McSection {
            name: "statusbar",
            entries: vec![entry("_default_", BACKGROUND, SPECIAL, &[])],
        },
        McSection {
            name: "help",
            entries: vec![
                entry("_default_", FOREGROUND, SURFACE, &[]),
                entry("helpitalic", WARNING, SURFACE, ITALIC),
                entry("helpbold", TYPE, SURFACE, BOLD),
                entry("helplink", SPECIAL, SURFACE, UNDERLINE),
                entry("helpslink", FOREGROUND, SPECIAL, &[]),
                entry("helptitle", TYPE, SURFACE, BOLD),
            ],
        },
        McSection {
            name: "editor",
            entries: vec![
                entry("_default_", FOREGROUND, BACKGROUND, &[]),
                entry("editbold", WARNING, BACKGROUND, BOLD),
                entry("editmarked", FOREGROUND, SELECTION, &[]),
                entry("editwhitespace", MUTED_FOREGROUND, BACKGROUND, &[]),
                entry("editnonprintable", MUTED_FOREGROUND, BACKGROUND, &[]),
                entry("editlinestate", BACKGROUND, SURFACE, &[]),
                entry("bookmark", FOREGROUND, ERROR, &[]),
                entry("bookmarkfound", BACKGROUND, GIT_ADDED, &[]),
                entry("editrightmargin", MUTED_FOREGROUND, SURFACE, &[]),
                entry("editbg", FOREGROUND, BACKGROUND, &[]),
                entry("editframe", MUTED_FOREGROUND, BACKGROUND, &[]),
                entry("editframeactive", BRIGHT_FOREGROUND, BACKGROUND, &[]),
                entry("editframedrag", ERROR, BACKGROUND, &[]),
            ],
        },
        McSection {
            name: "viewer",
            entries: vec![
                entry("_default_", FOREGROUND, BACKGROUND, &[]),
                entry("viewbold", WARNING, BACKGROUND, BOLD),
                entry("viewunderline", SPECIAL, BACKGROUND, UNDERLINE),
                entry("viewselected", FOREGROUND, SELECTION, &[]),
            ],
        },
        McSection {
            name: "diffviewer",
            entries: vec![
                entry("added", BACKGROUND, FILE_GIT_ADDED, &[]),
                entry("changedline", BACKGROUND, FILE_GIT_MODIFIED, &[]),
                entry("changednew", BACKGROUND, FILE_GIT_ADDED, &[]),
                entry("changed", BACKGROUND, FILE_GIT_MODIFIED, &[]),
                entry("removed", FOREGROUND, FILE_GIT_REMOVED, &[]),
                entry("error", FOREGROUND, ERROR, &[]),
            ],
        },
    ]
}

fn mc_colortable_entries() -> Vec<McColorTableEntry> {
    vec![
        color_table_entry("normal", FOREGROUND, BACKGROUND, &[]),
        color_table_entry("selected", FOREGROUND, SELECTION, &[]),
        color_table_entry("disabled", MUTED_FOREGROUND, SURFACE, &[]),
        color_table_entry("marked", WARNING, BACKGROUND, BOLD),
        color_table_entry("markselect", WARNING, SELECTION, BOLD),
        color_table_entry("errors", FOREGROUND, ERROR, &[]),
        color_table_entry("input", FOREGROUND, SURFACE, &[]),
        color_table_entry("inputmark", FOREGROUND, SELECTION, &[]),
        color_table_entry("inputunchanged", MUTED_FOREGROUND, SURFACE, &[]),
        color_table_entry("commandlinemark", FOREGROUND, SELECTION, &[]),
        color_table_entry("reverse", BACKGROUND, FOREGROUND, &[]),
        color_table_entry("gauge", FOREGROUND, SURFACE, &[]),
        color_table_entry("header", TYPE, BACKGROUND, BOLD),
        color_table_entry("inputhistory", FOREGROUND, SURFACE, &[]),
        color_table_entry("commandhistory", FOREGROUND, SURFACE, &[]),
        color_table_entry("bbarhotkey", WARNING, SURFACE, BOLD),
        color_table_entry("bbarbutton", FOREGROUND, SURFACE, &[]),
        color_table_entry("statusbar", BACKGROUND, SPECIAL, &[]),
        color_table_entry("menunormal", FOREGROUND, SURFACE, &[]),
        color_table_entry("menusel", FOREGROUND, SELECTION, &[]),
        color_table_entry("menuhot", WARNING, SURFACE, &[]),
        color_table_entry("menuhotsel", WARNING, SELECTION, &[]),
        color_table_entry("menuinactive", MUTED_FOREGROUND, SURFACE, &[]),
        color_table_entry("dnormal", FOREGROUND, SURFACE, &[]),
        color_table_entry("dfocus", BACKGROUND, SELECTION, BOLD),
        color_table_entry("dhotnormal", WARNING, SURFACE, &[]),
        color_table_entry("dhotfocus", WARNING, SELECTION, BOLD),
        color_table_entry("dtitle", TYPE, SURFACE, BOLD),
        color_table_entry("errdfocus", BACKGROUND, WARNING, BOLD),
        color_table_entry("errdhotnormal", WARNING, ERROR, &[]),
        color_table_entry("errdhotfocus", WARNING, SELECTION, BOLD),
        color_table_entry("errdtitle", WARNING, ERROR, BOLD),
        color_table_entry("helpnormal", FOREGROUND, SURFACE, &[]),
        color_table_entry("helpitalic", WARNING, SURFACE, ITALIC),
        color_table_entry("helpbold", TYPE, SURFACE, BOLD),
        color_table_entry("helplink", SPECIAL, SURFACE, UNDERLINE),
        color_table_entry("helpslink", FOREGROUND, SPECIAL, &[]),
        color_table_entry("helptitle", TYPE, SURFACE, BOLD),
        color_table_entry("viewnormal", FOREGROUND, BACKGROUND, &[]),
        color_table_entry("viewbold", WARNING, BACKGROUND, BOLD),
        color_table_entry("viewunderline", SPECIAL, BACKGROUND, UNDERLINE),
        color_table_entry("viewselected", FOREGROUND, SELECTION, &[]),
        color_table_entry("editnormal", FOREGROUND, BACKGROUND, &[]),
        color_table_entry("editbold", WARNING, BACKGROUND, BOLD),
        color_table_entry("editmarked", FOREGROUND, SELECTION, &[]),
        color_table_entry("editwhitespace", MUTED_FOREGROUND, BACKGROUND, &[]),
        color_table_entry("editnonprintable", MUTED_FOREGROUND, BACKGROUND, &[]),
        color_table_entry("editlinestate", BACKGROUND, SURFACE, &[]),
        color_table_entry("pmenunormal", FOREGROUND, SURFACE, &[]),
        color_table_entry("pmenusel", FOREGROUND, SELECTION, &[]),
        color_table_entry("pmenutitle", TYPE, SURFACE, BOLD),
    ]
}

#[derive(Debug)]
struct McFilehighlightGroup {
    section: &'static str,
    extensions: Vec<&'static str>,
}

fn mc_filehighlight_groups() -> Vec<McFilehighlightGroup> {
    let mut groups = vec![
        McFilehighlightGroup {
            section: "temp",
            extensions: Vec::new(),
        },
        McFilehighlightGroup {
            section: "archive",
            extensions: Vec::new(),
        },
        McFilehighlightGroup {
            section: "doc",
            extensions: Vec::new(),
        },
        McFilehighlightGroup {
            section: "source",
            extensions: Vec::new(),
        },
        McFilehighlightGroup {
            section: "media",
            extensions: Vec::new(),
        },
        McFilehighlightGroup {
            section: "graph",
            extensions: Vec::new(),
        },
        McFilehighlightGroup {
            section: "database",
            extensions: Vec::new(),
        },
    ];

    for group in file_extension_groups() {
        let Some(section) = mc_filehighlight_section(group.kind) else {
            continue;
        };
        if let Some(target) = groups.iter_mut().find(|target| target.section == section) {
            target.extensions.extend(group.extensions);
        }
    }

    groups
        .into_iter()
        .filter(|group| !group.extensions.is_empty())
        .collect()
}

fn mc_filehighlight_section(kind: FileKind) -> Option<&'static str> {
    match kind {
        FileKind::Archive => Some("archive"),
        FileKind::Document => Some("doc"),
        FileKind::Source => Some("source"),
        FileKind::Audio => Some("media"),
        FileKind::ImageVideo => Some("graph"),
        FileKind::Database => Some("database"),
        FileKind::Temporary => Some("temp"),
        _ => None,
    }
}

fn render_entry(entry: &McEntry, roles: &SemanticRoles, palette: &Base16Palette) -> String {
    let fg = resolve_color(entry.fg, roles, palette);
    let bg = resolve_color(entry.bg, roles, palette);
    if entry.attrs.is_empty() {
        format!("{fg};{bg}")
    } else {
        format!("{fg};{};{}", bg, entry.attrs.join("+"))
    }
}

fn resolve_color<'a>(
    mc_color: McColor,
    roles: &'a SemanticRoles,
    palette: &'a Base16Palette,
) -> &'a str {
    match mc_color {
        McColor::Role {
            roles: color_roles,
            fallback_base,
        } => {
            for role in color_roles {
                if let Some(color) = role_color(roles, *role) {
                    return color;
                }
            }
            color(palette, fallback_base)
        }
        McColor::FileKind(kind) => resolve_file_kind_color(kind, roles, palette),
    }
}

fn resolve_colortable_color(
    mc_color: McColor,
    roles: &SemanticRoles,
    palette: &Base16Palette,
) -> String {
    mc_256_color(resolve_color(mc_color, roles, palette))
}

fn mc_256_color(color: &str) -> String {
    let rgb = parse_rgb(color).expect("resolved exporter colors should be valid rgb hex colors");
    if rgb.r == rgb.g && rgb.g == rgb.b {
        return format!("gray{}", quantize(rgb.r, 23));
    }

    format!(
        "rgb{}{}{}",
        quantize(rgb.r, 5),
        quantize(rgb.g, 5),
        quantize(rgb.b, 5)
    )
}

fn quantize(component: u8, max: u8) -> u8 {
    ((component as u16 * max as u16 + 127) / 255) as u8
}

fn mc_preserved_items(roles: &SemanticRoles) -> Vec<PreservedItem> {
    let mut items = Vec::new();
    for section in mc_sections() {
        for entry in section.entries {
            push_source(&mut items, roles, section.name, entry.key, "fg", entry.fg);
            push_source(&mut items, roles, section.name, entry.key, "bg", entry.bg);
        }
    }
    items
}

fn push_source(
    items: &mut Vec<PreservedItem>,
    roles: &SemanticRoles,
    section: &str,
    key: &str,
    property: &str,
    mc_color: McColor,
) {
    let target = format!("{section}.{key}.{property}");
    match mc_color {
        McColor::Role {
            roles: color_roles, ..
        } => {
            for role in color_roles {
                if let Some(value) = roles.get(role) {
                    if let Some(source) = role_source(value) {
                        items.push(PreservedItem { target, source });
                        break;
                    }
                }
            }
        }
        McColor::FileKind(kind) => push_file_kind_source(items, roles, &target, kind),
    }
}

fn mc_dropped_items(theme: &ResolvedTheme) -> Vec<String> {
    let mut dropped = dropped_items(theme);
    dropped.push("Helix syntax scopes collapse to Midnight Commander UI fields".to_owned());
    dropped.push("Helix underline styles collapse to Midnight Commander underline".to_owned());
    dropped.push("Helix dim, crossed-out, and reversed modifiers are not represented".to_owned());
    dropped.push("MC_COLOR_TABLE quantizes truecolor values to MC 256-color tokens".to_owned());
    dropped
}
