use crate::file_kinds::{push_file_kind_source, resolve_file_kind_color, FileKind};
use crate::report::{dropped_items, role_source, ExportReport, PreservedItem};
use palette16::{color, Base16Palette};
use semantic_roles::{role_color, Role, SemanticRoles};
use theme_ir::{ResolvedTheme, Warning};

pub fn export_mc_skin(
    theme: &ResolvedTheme,
    roles: &SemanticRoles,
    palette: &Base16Palette,
    warnings: Vec<Warning>,
) -> (String, ExportReport) {
    let mut output = String::new();
    output.push_str("[skin]\n");
    output.push_str(&format!(
        "    description = {} - generated by Helix Theme Transformer\n",
        theme.name
    ));
    output.push_str("    truecolors = true\n");
    output.push('\n');
    output.push_str("[Lines]\n");
    for (key, value) in mc_lines() {
        output.push_str(&format!("    {key} = {value}\n"));
    }

    for section in mc_sections() {
        output.push('\n');
        output.push_str(&format!("[{}]\n", section.name));
        for entry in section.entries {
            output.push_str(&format!(
                "    {} = {}\n",
                entry.key,
                render_entry(&entry, roles, palette)
            ));
        }
    }

    let report = ExportReport {
        exporter: "mc".to_owned(),
        source: theme.source_path.to_string(),
        preserved: mc_preserved_items(roles),
        dropped: mc_dropped_items(theme),
        warnings,
    };
    (output, report)
}

#[derive(Debug, Clone)]
struct McSection {
    name: &'static str,
    entries: Vec<McEntry>,
}

#[derive(Debug, Clone, Copy)]
struct McEntry {
    key: &'static str,
    fg: McColor,
    bg: McColor,
    attrs: &'static [&'static str],
}

#[derive(Debug, Clone, Copy)]
enum McColor {
    Role {
        roles: &'static [Role],
        fallback_base: &'static str,
    },
    FileKind(FileKind),
}

impl McColor {
    const fn new(roles: &'static [Role], fallback_base: &'static str) -> Self {
        Self::Role {
            roles,
            fallback_base,
        }
    }

    const fn file_kind(kind: FileKind) -> Self {
        Self::FileKind(kind)
    }
}

const BACKGROUND: McColor = McColor::new(&[Role::Background], "base00");
const SURFACE: McColor = McColor::new(&[Role::Surface], "base01");
const SELECTION: McColor = McColor::new(&[Role::Selection], "base02");
const FOREGROUND: McColor = McColor::new(&[Role::Foreground], "base05");
const MUTED_FOREGROUND: McColor = McColor::new(&[Role::MutedForeground], "base03");
const BRIGHT_FOREGROUND: McColor = McColor::new(&[Role::BrightForeground], "base07");
const TYPE: McColor = McColor::new(&[Role::Type], "base0A");
const SPECIAL: McColor = McColor::new(&[Role::Special], "base0C");
const ERROR: McColor = McColor::new(&[Role::Error], "base08");
const WARNING: McColor = McColor::new(&[Role::Warning, Role::Type], "base0A");
const GIT_ADDED: McColor = McColor::new(&[Role::GitAdded], "base0B");
const FILE_DIRECTORY: McColor = McColor::file_kind(FileKind::Directory);
const FILE_SYMLINK: McColor = McColor::file_kind(FileKind::Symlink);
const FILE_EXECUTABLE: McColor = McColor::file_kind(FileKind::Executable);
const FILE_DEVICE: McColor = McColor::file_kind(FileKind::Device);
const FILE_BROKEN_LINK: McColor = McColor::file_kind(FileKind::BrokenLink);
const FILE_ARCHIVE: McColor = McColor::file_kind(FileKind::Archive);
const FILE_DOCUMENT: McColor = McColor::file_kind(FileKind::Document);
const FILE_SOURCE: McColor = McColor::file_kind(FileKind::Source);
const FILE_IMAGE_VIDEO: McColor = McColor::file_kind(FileKind::ImageVideo);
const FILE_DATABASE: McColor = McColor::file_kind(FileKind::Database);
const FILE_TEMPORARY: McColor = McColor::file_kind(FileKind::Temporary);
const FILE_GIT_ADDED: McColor = McColor::file_kind(FileKind::GitAdded);
const FILE_GIT_MODIFIED: McColor = McColor::file_kind(FileKind::GitModified);
const FILE_GIT_REMOVED: McColor = McColor::file_kind(FileKind::GitRemoved);

const BOLD: &[&str] = &["bold"];
const ITALIC: &[&str] = &["italic"];
const UNDERLINE: &[&str] = &["underline"];

fn mc_lines() -> &'static [(&'static str, &'static str)] {
    &[
        ("horiz", "─"),
        ("vert", "│"),
        ("lefttop", "┌"),
        ("righttop", "┐"),
        ("leftbottom", "└"),
        ("rightbottom", "┘"),
        ("topmiddle", "┬"),
        ("bottommiddle", "┴"),
        ("leftmiddle", "├"),
        ("rightmiddle", "┤"),
        ("cross", "┼"),
        ("dhoriz", "═"),
        ("dvert", "║"),
        ("dlefttop", "╔"),
        ("drighttop", "╗"),
        ("dleftbottom", "╚"),
        ("drightbottom", "╝"),
        ("dtopmiddle", "╤"),
        ("dbottommiddle", "╧"),
        ("dleftmiddle", "╟"),
        ("drightmiddle", "╢"),
    ]
}

const fn entry(key: &'static str, fg: McColor, bg: McColor, attrs: &'static [&str]) -> McEntry {
    McEntry { key, fg, bg, attrs }
}

fn mc_sections() -> Vec<McSection> {
    vec![
        McSection {
            name: "core",
            entries: vec![
                entry("_default_", FOREGROUND, BACKGROUND, &[]),
                entry("selected", FOREGROUND, SELECTION, &[]),
                entry("marked", WARNING, BACKGROUND, BOLD),
                entry("markselect", WARNING, SELECTION, BOLD),
                entry("gauge", FOREGROUND, SURFACE, &[]),
                entry("input", FOREGROUND, SURFACE, &[]),
                entry("inputmark", FOREGROUND, SELECTION, &[]),
                entry("inputunchanged", MUTED_FOREGROUND, SURFACE, &[]),
                entry("disabled", MUTED_FOREGROUND, SURFACE, &[]),
                entry("reverse", BACKGROUND, FOREGROUND, &[]),
                entry("commandlinemark", FOREGROUND, SELECTION, &[]),
                entry("header", TYPE, BACKGROUND, BOLD),
                entry("shadow", MUTED_FOREGROUND, BACKGROUND, &[]),
            ],
        },
        McSection {
            name: "dialog",
            entries: vec![
                entry("_default_", FOREGROUND, SURFACE, &[]),
                entry("dfocus", BACKGROUND, SELECTION, BOLD),
                entry("dhotnormal", WARNING, SURFACE, &[]),
                entry("dhotfocus", WARNING, SELECTION, BOLD),
                entry("dtitle", TYPE, SURFACE, BOLD),
            ],
        },
        McSection {
            name: "error",
            entries: vec![
                entry("_default_", FOREGROUND, ERROR, &[]),
                entry("errdfocus", BACKGROUND, WARNING, BOLD),
                entry("errdhotnormal", WARNING, ERROR, &[]),
                entry("errdhotfocus", WARNING, SELECTION, BOLD),
                entry("errdtitle", WARNING, ERROR, BOLD),
            ],
        },
        McSection {
            name: "filehighlight",
            entries: vec![
                entry("directory", FILE_DIRECTORY, BACKGROUND, BOLD),
                entry("executable", FILE_EXECUTABLE, BACKGROUND, BOLD),
                entry("symlink", FILE_SYMLINK, BACKGROUND, &[]),
                entry("hardlink", FILE_SYMLINK, BACKGROUND, &[]),
                entry("stalelink", FILE_BROKEN_LINK, BACKGROUND, &[]),
                entry("device", FILE_DEVICE, BACKGROUND, &[]),
                entry("special", FILE_SYMLINK, BACKGROUND, &[]),
                entry("core", FILE_BROKEN_LINK, BACKGROUND, &[]),
                entry("temp", FILE_TEMPORARY, BACKGROUND, &[]),
                entry("archive", FILE_ARCHIVE, BACKGROUND, &[]),
                entry("doc", FILE_DOCUMENT, BACKGROUND, &[]),
                entry("source", FILE_SOURCE, BACKGROUND, &[]),
                entry("media", FILE_IMAGE_VIDEO, BACKGROUND, &[]),
                entry("graph", FILE_IMAGE_VIDEO, BACKGROUND, &[]),
                entry("database", FILE_DATABASE, BACKGROUND, &[]),
            ],
        },
        McSection {
            name: "menu",
            entries: vec![
                entry("_default_", FOREGROUND, SURFACE, &[]),
                entry("menusel", FOREGROUND, SELECTION, &[]),
                entry("menuhot", WARNING, SURFACE, &[]),
                entry("menuhotsel", WARNING, SELECTION, &[]),
                entry("menuinactive", MUTED_FOREGROUND, SURFACE, &[]),
            ],
        },
        McSection {
            name: "popupmenu",
            entries: vec![
                entry("_default_", FOREGROUND, SURFACE, &[]),
                entry("menusel", FOREGROUND, SELECTION, &[]),
                entry("menutitle", TYPE, SURFACE, BOLD),
            ],
        },
        McSection {
            name: "buttonbar",
            entries: vec![
                entry("hotkey", WARNING, SURFACE, BOLD),
                entry("button", FOREGROUND, SURFACE, &[]),
            ],
        },
        McSection {
            name: "statusbar",
            entries: vec![entry("_default_", BACKGROUND, SPECIAL, &[])],
        },
        McSection {
            name: "help",
            entries: vec![
                entry("_default_", FOREGROUND, SURFACE, &[]),
                entry("helpitalic", WARNING, SURFACE, ITALIC),
                entry("helpbold", TYPE, SURFACE, BOLD),
                entry("helplink", SPECIAL, SURFACE, UNDERLINE),
                entry("helpslink", FOREGROUND, SPECIAL, &[]),
                entry("helptitle", TYPE, SURFACE, BOLD),
            ],
        },
        McSection {
            name: "editor",
            entries: vec![
                entry("_default_", FOREGROUND, BACKGROUND, &[]),
                entry("editbold", WARNING, BACKGROUND, BOLD),
                entry("editmarked", FOREGROUND, SELECTION, &[]),
                entry("editwhitespace", MUTED_FOREGROUND, BACKGROUND, &[]),
                entry("editnonprintable", MUTED_FOREGROUND, BACKGROUND, &[]),
                entry("editlinestate", BACKGROUND, SURFACE, &[]),
                entry("bookmark", FOREGROUND, ERROR, &[]),
                entry("bookmarkfound", BACKGROUND, GIT_ADDED, &[]),
                entry("editrightmargin", MUTED_FOREGROUND, SURFACE, &[]),
                entry("editbg", FOREGROUND, BACKGROUND, &[]),
                entry("editframe", MUTED_FOREGROUND, BACKGROUND, &[]),
                entry("editframeactive", BRIGHT_FOREGROUND, BACKGROUND, &[]),
                entry("editframedrag", ERROR, BACKGROUND, &[]),
            ],
        },
        McSection {
            name: "viewer",
            entries: vec![
                entry("_default_", FOREGROUND, BACKGROUND, &[]),
                entry("viewbold", WARNING, BACKGROUND, BOLD),
                entry("viewunderline", SPECIAL, BACKGROUND, UNDERLINE),
                entry("viewselected", FOREGROUND, SELECTION, &[]),
            ],
        },
        McSection {
            name: "diffviewer",
            entries: vec![
                entry("added", BACKGROUND, FILE_GIT_ADDED, &[]),
                entry("changedline", BACKGROUND, FILE_GIT_MODIFIED, &[]),
                entry("changednew", BACKGROUND, FILE_GIT_ADDED, &[]),
                entry("changed", BACKGROUND, FILE_GIT_MODIFIED, &[]),
                entry("removed", FOREGROUND, FILE_GIT_REMOVED, &[]),
                entry("error", FOREGROUND, ERROR, &[]),
            ],
        },
    ]
}

fn render_entry(entry: &McEntry, roles: &SemanticRoles, palette: &Base16Palette) -> String {
    let fg = resolve_color(entry.fg, roles, palette);
    let bg = resolve_color(entry.bg, roles, palette);
    if entry.attrs.is_empty() {
        format!("{fg};{bg}")
    } else {
        format!("{fg};{};{}", bg, entry.attrs.join("+"))
    }
}

fn resolve_color<'a>(
    mc_color: McColor,
    roles: &'a SemanticRoles,
    palette: &'a Base16Palette,
) -> &'a str {
    match mc_color {
        McColor::Role {
            roles: color_roles,
            fallback_base,
        } => {
            for role in color_roles {
                if let Some(color) = role_color(roles, *role) {
                    return color;
                }
            }
            color(palette, fallback_base)
        }
        McColor::FileKind(kind) => resolve_file_kind_color(kind, roles, palette),
    }
}

fn mc_preserved_items(roles: &SemanticRoles) -> Vec<PreservedItem> {
    let mut items = Vec::new();
    for section in mc_sections() {
        for entry in section.entries {
            push_source(&mut items, roles, section.name, entry.key, "fg", entry.fg);
            push_source(&mut items, roles, section.name, entry.key, "bg", entry.bg);
        }
    }
    items
}

fn push_source(
    items: &mut Vec<PreservedItem>,
    roles: &SemanticRoles,
    section: &str,
    key: &str,
    property: &str,
    mc_color: McColor,
) {
    let target = format!("{section}.{key}.{property}");
    match mc_color {
        McColor::Role {
            roles: color_roles, ..
        } => {
            for role in color_roles {
                if let Some(value) = roles.get(role) {
                    if let Some(source) = role_source(value) {
                        items.push(PreservedItem { target, source });
                        break;
                    }
                }
            }
        }
        McColor::FileKind(kind) => push_file_kind_source(items, roles, &target, kind),
    }
}

fn mc_dropped_items(theme: &ResolvedTheme) -> Vec<String> {
    let mut dropped = dropped_items(theme);
    dropped.push("Helix syntax scopes collapse to Midnight Commander UI fields".to_owned());
    dropped.push("Helix underline styles collapse to Midnight Commander underline".to_owned());
    dropped.push("Helix dim, crossed-out, and reversed modifiers are not represented".to_owned());
    dropped
}
